### ISSUE TITLE
in meditation

### ISSUE THREAD

**Issue by imeetsanghvi** [CANIS-NAU/ARORA-App#16]
remove start text
align start button
figure out how to remove the back button loop 

default 3 minutes (no other options)

**Comment by DariusDumel** [comment]
![image](https://user-images.githubusercontent.com/25535561/120874407-5e511500-c55b-11eb-9e42-cb66e2bee477.png)
removed start text and changed the only time to 3 minutes. I''m not sure how the start button isn't aligned but i made sure the constraints were set.

![image](https://user-images.githubusercontent.com/25535561/120874444-8fc9e080-c55b-11eb-9375-d96246317561.png)
back button loop was being caused by the exit button creating a new intent instead of popping the current intent above is the change i made to correct this.
